### ISSUE TITLE
idk what is  making not load :/

### ISSUE THREAD

**Issue by Zassdio** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#45]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-08-09 05:26:56
Description: Rendering overlay

com.google.gson.JsonSyntaxException: Expected vector to be a JsonArray, was an object ({"ve...1]})
	at net.minecraft.util.GsonHelper.convertToJsonArray(GsonHelper.java:354) ~[forge-1.19.4-45.1.0_mapped_official_1.19.4-recomp.jar%23189!/:?] {re:classloading}
	at net.minecraft.util.GsonHelper.getAsJsonArray(GsonHelper.java:360) ~[forge-1.19.4-45.1.0_mapped_official_1.19.4-recomp.jar%23189!/:?] {re:classloading}
	at software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.buildKeyframeStack(BakedAnimationsAdapter.java:149) ~[geckolib-forge-1.19.4-4.1.3_mapped_official_1.19.4.jar%23197!/:4.1.3] {re:classloading}
	at software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.bakeBoneAnimations(BakedAnimationsAdapter.java:68) ~[geckolib-forge-1.19.4-4.1.3_mapped_official_1.19.4.jar%23197!/:4.1.3] {re:classloading}
	at software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.bakeAnimation(BakedAnimationsAdapter.java:53) ~[geckolib-forge-1.19.4-4.1.3_mapped_official_1.19.4.jar%23197!/:4.1.3] {re:classloading}
	at software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:39) ~[geckolib-forge-1.19.4-4.1.3_mapped_official_1.19.4.jar%23197!/:4.1.3] {re:classloading}
	at software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.deserialize(BakedAnimationsAdapter.java:31) ~[geckolib-forge-1.19.4-4.1.3_mapped_official_1.19.4.jar%23197!/:4.1.3] {re:classloading}
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%23128!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar%23128!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar%23128!/:?] {}
	at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar%23128!/:?] {}
	at software.bernie.geckolib.loading.FileLoader.loadAnimationsFile(FileLoader.java:28) ~[geckolib-forge-1.19.4-4.1.3_mapped_official_1.19.4.jar%23197!/:4.1.3] {re:classloading}
	at software.bernie.geckolib.cache.GeckoLibCache.lambda$loadAnimations$1(GeckoLibCache.java:90) ~[geckolib-forge-1.19.4-4.1.3_mapped_official_1.19.4.jar%23197!/:4.1.3] {re:classloading}
	at software.bernie.geckolib.cache.GeckoLibCache.lambda$loadResources$5(GeckoLibCache.java:112) ~[geckolib-forge-1.19.4-4.1.3_mapped_official_1.19.4.jar%23197!/:4.1.3] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.util.GsonHelper.convertToJsonArray(GsonHelper.java:354) ~[forge-1.19.4-45.1.0_mapped_official_1.19.4-recomp.jar%23189!/:?] {re:classloading}
	at net.minecraft.util.GsonHelper.getAsJsonArray(GsonHelper.java:360) ~[forge-1.19.4-45.1.0_mapped_official_1.19.4-recomp.jar%23189!/:?] {re:classloading}
	at software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.buildKeyframeStack(BakedAnimationsAdapter.java:149) ~[geckolib-forge-1.19.4-4.1.3_mapped_official_1.19.4.jar%23197!/:4.1.3] {re:classloading}
	at software.bernie.geckolib.loading.json.typeadapter.BakedAnimationsAdapter.bakeBoneAnimations(BakedAnimationsAdapter.java:68) ~[geckolib-forge-1.19.4-4.1.3_mapped_official_1.19.4.jar%23197!/:4.1.3] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:943) ~[forge-1.19.4-45.1.0_mapped_official_1.19.4-recomp.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.GameRendererMixin,pl:mixin:APP:pehkui.mixins.json:client.compat1193plus.GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1148) ~[forge-1.19.4-45.1.0_mapped_official_1.19.4-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:719) ~[forge-1.19.4-45.1.0_mapped_official_1.19.4-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[forge-1.19.4-45.1.0_mapped_official_1.19.4-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:25) ~[fmlloader-1.19.4-45.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, mod_resources

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.5, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 314619552 bytes (300 MiB) / 617611264 bytes (589 MiB) up to 2118123520 bytes (2020 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: Whiskey Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Parsec Virtual Display Adapter
	Graphics card #0 vendor: Parsec Cloud, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=0.38.0.0
	Graphics card #1 name: Intel(R) UHD Graphics 620
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3ea0
	Graphics card #1 versionInfo: DriverVersion=31.0.101.2114
	Graphics card #2 name: NVIDIA GeForce MX110
	Graphics card #2 vendor: NVIDIA (0x10de)
	Graphics card #2 VRAM (MB): 2048.00
	Graphics card #2 deviceId: 0x174e
	Graphics card #2 versionInfo: DriverVersion=30.0.15.1277
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22575.85
	Virtual memory used (MB): 14632.06
	Swap memory total (MB): 14503.61
	Swap memory used (MB): 1437.18
	JVM Flags: 1 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Launched Version: MOD_DEV
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Intel(R) UHD Graphics 620 GL version 3.2.0 - Build 31.0.101.2114, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: en_us
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclientuserdev
	ModLauncher naming: mcp
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.1.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.1.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.1.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.1.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.1.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		forge-1.19.4-45.1.0_mapped_official_1.19.4-recomp.|Minecraft                     |minecraft                     |1.19.4              |SIDED_SETU|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Pehkui-3.7.4-1.19.4-forge_mapped_official_1.19.4.j|Pehkui                        |pehkui                        |3.7.4+1.19.4-forge  |SIDED_SETU|Manifest: NOSIGNATURE
		                                                  |Forge                         |forge                         |45.1.0              |SIDED_SETU|Manifest: NOSIGNATURE
		main                                              |minecraft plus                |minecraft_plus                |1.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-1.19.4-5.1.5.2_mapped_official_1.19.4|Curios API                    |curios                        |1.19.4-5.1.5.2      |SIDED_SETU|Manifest: NOSIGNATURE
		geckolib-forge-1.19.4-4.1.3_mapped_official_1.19.4|GeckoLib 4                    |geckolib                      |4.1.3               |SIDED_SETU|Manifest: NOSIGNATURE
	Crash Report UUID: 42f4f0a2-8f32-40ed-8e0b-12635bd925a6
	FML: 45.1
	Forge: net.minecraftforge:45.1.0

**Comment by NerdyPuzzle** [comment]
You have a broken animation file. But this is not the place to ask for support, it is for reporting plugin issues.
